# Generated by Django 6.0.7 on 2026-09-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_url',
            field=models.URLField(blank=True, help_text="Where attendees can buy tickets for this event (RF21). Leave empty if there's no ticketing link."),
        ),
    ]
