# Generated by Django 6.0.7 on 2026-08-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_latitude_event_longitude_accommodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='End date and time, for multi-day events (fairs, festivals). Leave empty for single-day events.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(help_text='Start date and time (required).'),
        ),
    ]
